### ISSUE TITLE
Add setUpdateOperator in claim function?

### ISSUE THREAD

**Issue by LiRiu** [decentraland/rentals-contract#63]
when rental end, owner of asset need invoke claim functions && setUpdateOperator functions to revoke operator permissions.

How about insert setUpdateOperator into claim function? 

from this

https://github.com/decentraland/rentals-contract/blob/9f92af7b5405cd18044615ea3351627521797e37/contracts/Rentals.sol#L257-L280

to this

```
    function claim(address _contractAddress, uint256 _tokenId) external {
        ...
        IERC721 asset = IERC721(_contractAddress);

        asset.setUpdateOperator(_tokenId, sender);  // add this line?

        asset.safeTransferFrom(address(this), sender, _tokenId);
        ....
    }
```

In this way, while reducing gas consumption, it protects the unwary lessor who forgot to revoke permission, and the tenant will get an extra lease term that exceeds expectations.

**Comment by nachomazzara** [comment]
The `updateOperator` is being removed on every transfer by the nft contract
